CREATE TABLE IF NOT EXISTS CONCEPTS (
    id SERIAL,
    val VARCHAR
);

CREATE TABLE IF NOT EXISTS NODES (
    id SERIAL,
    val VARCHAR
);

CREATE TABLE IF NOT EXISTS PROPERTIES (
    id SERIAL,
    val VARCHAR
);